export const excelColumnDefinitions = [
  { excelField: 'SEQNO', label: 'Seq.', prismaField: 'seqno' },
  { excelField: 'ARBPL', label: 'Work center', prismaField: 'arbpl' },
  { excelField: 'AUFNR', label: 'Order', prismaField: 'aufnr' },
  { excelField: 'TEXT1', label: 'Status', prismaField: 'text1' },
  { excelField: 'ZPMAT', label: 'เหล็กอาบ', prismaField: 'zpmat' },
  { excelField: 'ZPTKX', label: 'Description 1', prismaField: 'zptkx' },
  { excelField: 'ZPTXT', label: 'Description 2', prismaField: 'zptxt' },
  { excelField: 'ZPG1D', label: 'Group 1', prismaField: 'zpg1d' },
  { excelField: 'ZPG2D', label: 'Group 2', prismaField: 'zpg2d' },
  { excelField: 'ZPG3D', label: 'Group 3', prismaField: 'zpg3d' },
  { excelField: 'ZPG4D', label: 'Group 4', prismaField: 'zpg4d' },
  { excelField: 'ZPG5D', label: 'Group 5', prismaField: 'zpg5d' },
  { excelField: 'STDATE', label: 'Start Date', prismaField: 'stdate' },
  { excelField: 'FINDATE', label: 'Finish Date', prismaField: 'findate' },
  { excelField: 'PRDDAY', label: 'PRD.(Days)', prismaField: 'prdday' },
  { excelField: 'STEEL_DIB_ID', label: 'เหล็กดิบ', prismaField: 'steelDibId' },
  { excelField: 'STEEL_DIB_DESC', label: 'Description 1', prismaField: 'steelDibDesc' },
  { excelField: 'STEEL_DIB_LONG', label: 'Description 2', prismaField: 'steelDibLong' },
  { excelField: 'ZLMAT', label: 'Lacquer', prismaField: 'zlmat' },
  { excelField: 'ZLTKX', label: 'Description', prismaField: 'zltkx' },
  { excelField: 'ZLG3D', label: 'Group 3', prismaField: 'zlg3d' },
  { excelField: 'ZLG5D', label: 'Group 5', prismaField: 'zlg5d' },
  { excelField: 'VORNR', label: 'OP', prismaField: 'vornr' },
  { excelField: 'LTXA1', label: 'OP DESC', prismaField: 'ltxa1' },
  { excelField: 'USR00', label: 'FW.', prismaField: 'usr00' },
  { excelField: 'USR02', label: 'TEMP', prismaField: 'usr02' },
  { excelField: 'TIME', label: 'Op. (HR)', prismaField: 'time' },
  { excelField: 'OPTIME', label: 'Op. Time', prismaField: 'optime' },
  { excelField: 'OPDAYS', label: 'Op. Days', prismaField: 'opdays' },
  { excelField: 'MGVRG', label: 'Order Quantity', prismaField: 'mgvrg' },
  { excelField: 'REMARK', label: 'Remark', prismaField: 'remark' },
  { excelField: 'PRIORITY', label: 'Priority', prismaField: 'priority' },
  { excelField: 'ENTD', label: 'Re-arrange Date', prismaField: 'entd' },
  { excelField: 'ZVERS', label: 'Version', prismaField: 'zvers' },
  { excelField: 'CONFIRM_YIELD', label: 'Yield', prismaField: 'confirmYield' },
  { excelField: 'CONFIRM_HOLD', label: 'Hold', prismaField: 'confirmHold' },
  { excelField: 'CONFIRM_SCRAP', label: 'Scrap', prismaField: 'confirmScrap' },
] as const;

export const requiredExcelHeaders = excelColumnDefinitions.map((column) => column.excelField);
